---
title: "1_Data_Visualization"
author: "JinHeon Yoon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: true
    toc_depth: 4
    toc_float: true
highlight: textmate
theme: cosmo
header-includes: \usepackage{kotex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, fig.align = "center", message=F, warning=F, fig.height = 8, cache=T, dpi = 300)
```

## 1.1 **들어가기**

>quote<- "간단한 그래프는 데이터 분석가에게 다른 어떤 것보다도 많은 정보를 제공한다." -John Tukey -

### 1.1.1 준비하기_타이디버스 로드하기

```{r}

library(tidyverse)
library(ggplot2)

```

## 1.2 **첫단계**

### 1.2.1 mpg 데이터 프레임
데이터 프레임은 변수들(열)과 관측값(행)의 직사각형 모음이다

### 1.2.2 **ggplot 생성하기**
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy))

```

엔진크기가 클 수록 연비가 낮게 나타난다.
 
  * displ : engine displacement, 엔진크기
  *  hwy : highway miles per gallon, 고속도로에서의 자동차 연비

###1.2.3 그래프 작성 템플릿

ggplot(data = <데이터>)+
  지옴함수(mapping = aes(<매핑모음>)) 

ggplot의 기본적인 템플릿은 다음과 같다
### 1.2.4 연습문제
```{r}
library(ggplot2)
ggplot(data = mpg)+
  geom_point(mapping = aes(x=hwy,y=cyl))

ggplot(data = mpg)+
  geom_point(mapping = aes(x=class,y=cyl))


```

## 1.3 심미성 매핑
 > "그래프의 가장 큰 가치는 전혀 예상하지 못한 것을 보여줄 때이다." -John Tukey-

//

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy,color=class))
```

국